### PR TITLE
define configurable channels

### PR DESCRIPTION
**Pull request by jerpelea**
Those changes are a first step to be able to use libsamplerate with NuttX RTOS

### CODE REVIEW

**Comment by acassis** [comment]
Very nice @jerpelea ! Do you plan to integrate libsndfile on NuttX in the same way LVGL and other were added? Like a external library?

**Comment by jerpelea** [comment]
that is my plan for several external libs

**Comment by jerpelea** [comment]
@evpobr do you mind helping us geting the needed patches in

**Comment by evpobr** [comment]
> @evpobr do you mind helping us geting the needed patches in

Hi, @jerpelea. Ping me when you're done.

**Comment by jerpelea** [comment]
@evpobr first one is ready

**Comment by evpobr** [comment]
Test fails.

**Comment by jerpelea** [comment]
@evpobr I kicked out the extra patch 
please refresh the page

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Thnaks @jerpelea

**Pull request merged**
