### PR TITLE
Implement SSE2 lrint() and lrintf()

### LINKED ISSUE #187: Slow `lrint()` `lrintf()` functions in the release Windows build.
The `SRC_LINEAR` method is about 10 times slower in the default MSVC build compared to the MinGW64 build. MinGW64 uses custom `lrint()` [implementation](https://github.com/mingw-w64/mingw-w64/blob/4359b3570a717d20dcb4251f5b5e94459e1a64ac/mingw-w64-headers/crt/math.h#L977-L983). To solve this problem, I suggest adding [/fp:fast](https://learn.microsoft.com/en-us/cpp/build/reference/fp-specify-floating-point-behavior?view=msvc-170#fast) option:
```
if(MSVC)
  add_compile_options("/fp:fast")
endif()
```
An alternative solution is probably to resurrect the `float_cast.h` file for the MSVC case?

### PR DESCRIPTION
**Pull request by rfomin**
Fix #187

### CODE REVIEW

**Review by erikd — COMMENTED** [review]
LGTM.

**Comment by erikd** [comment]
The used to have CI on this project. I think Travis (the old CI) has disappeared, but it should be possible to do something with Github Actions (even if its just Linux, which should be the easiest).

**Comment by rfomin** [comment]
> The used to have CI on this project.

It looks like CI is here: https://github.com/libsndfile/libsamplerate/blob/master/.github/workflows/build.yml
Someone just needs to approve running workflow, I'm first time contributor.

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Errors are unrelated to PR. We need to update CI.

**Comment by evpobr** [comment]
Thanks @rfomin !

**Comment by sezero** [comment]
The patch here might be OK for x86_64, but it doesn't give us disabling SSE2
code for x86 builds: I suggest some configury switch like --enable-sse2 (and an
equivalent of it in cmake.)

**Pull request merged**
