### PR TITLE
use sse2 intrinsics for lrint/lrintf only on windows x64

### PR DESCRIPTION
**Pull request by sezero**
Fixes https://github.com/libsndfile/libsamplerate/issues/187
Fixes https://github.com/libsndfile/libsamplerate/pull/188
Fixes https://github.com/libsndfile/libsamplerate/issues/191

CC: @rfomin

### CODE REVIEW

**Comment by rfomin** [comment]
LGTM

**Comment by evpobr** [comment]
Do we really need to limit SSE2 to x64?

https://github.com/libsndfile/libsndfile/blob/71f7bde180ade1869542d36483bc2e2c809c2189/cmake/CheckCPUArch.cmake#L17-L23

**Comment by sezero** [comment]
> Do we really need to limit SSE2 to x64?

No, we don't. But can you guarantee that `__SSE2__` is defined on x86?

**Comment by sezero** [comment]
> > Do we really need to limit SSE2 to x64?
> 
> No, we don't. But can you guarantee that `__SSE2__` is defined on x86?

E.g.: see the build error I noted in #191

**Comment by sezero** [comment]
Any verdict ?

**Comment by evpobr** [comment]
Not always: https://stackoverflow.com/questions/18563978/detect-the-availability-of-sse-sse2-instruction-set-in-visual-studio

**Comment by evpobr** [comment]
> Any verdict ?

Not sure redefining lrintf is good idea.

**Comment by sezero** [comment]
> Not sure redefining lrintf is good idea.

I don't see the harm since we're doing it privately - but if you want static inlines, tell me.

**Comment by sezero** [comment]
Anyways, I force-pushed a version that keeps the inlines as inlines - no redefines.

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Thanks @sezero !

**Pull request merged**
