### PR TITLE
configure (autotools) updates for windows

### PR DESCRIPTION
**Pull request by sezero**
- configure.ac: add `-export-symbols Win32/libsamplerate-0.def` to libtool link flags
- Win32/Makefile.mingw.in: remove. autotools work fine now.
- configure.ac: remove broken dllwrap, etc detection: not needed anymore.

### CODE REVIEW

**Comment by sezero** [comment]
PING?

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Hi @sezero , sorry for delay.

This is a great pull request. If that's all, I'm ready to merge it.

**Comment by sezero** [comment]
> Hi @sezero , sorry for delay.
> 
> This is a great pull request.

Thanks.

> If that's all, I'm ready to merge it.

Nothing else I can think of at the moment.

**Comment by evpobr** [comment]
Thanks!

**Pull request merged**
