### PR TITLE
Some grammatical errors are fixed.

### PR DESCRIPTION
**Pull request by varikvalefor**

### CODE REVIEW

**Review by evpobr — APPROVED** [review]

**Comment by evpobr** [comment]
Hi @varikvalefor , thanks for this :smile:

**Comment by varikvalefor** [comment]
> Hi @varikvalefor , thanks for this

De nada.

**Comment by evpobr** [comment]
> > Hi @varikvalefor , thanks for this
> 
> De nada.

Wow. spanish?

**Comment by evpobr** [comment]
Без проблем :smile:

**Review by SoapGentoo — APPROVED** [review]

**Pull request merged**
