### PR TITLE
Release 0.2.2

### PR DESCRIPTION
**Pull request by SoapGentoo**
Autotools:
```
tmp/
└── usr
    └── local
        ├── include
        │   └── samplerate.h
        ├── lib
        │   ├── libsamplerate.la
        │   ├── libsamplerate.so -> libsamplerate.so.0.2.2
        │   ├── libsamplerate.so.0 -> libsamplerate.so.0.2.2
        │   ├── libsamplerate.so.0.2.2
        │   └── pkgconfig
        │       └── samplerate.pc
```

CMake:
```
tmp/
└── usr
    └── local
        ├── include
        │   └── samplerate.h
        ├── lib64
        │   ├── cmake
        │   │   └── SampleRate
        │   │       ├── SampleRateConfig.cmake
        │   │       ├── SampleRateConfigVersion.cmake
        │   │       ├── SampleRateTargets.cmake
        │   │       └── SampleRateTargets-noconfig.cmake
        │   ├── libsamplerate.so -> libsamplerate.so.0
        │   ├── libsamplerate.so.0 -> libsamplerate.so.0.2.2
        │   ├── libsamplerate.so.0.2.2
        │   └── pkgconfig
        │       └── samplerate.pc
```

### CODE REVIEW

**Review by evpobr — CHANGES_REQUESTED** [review]
`docs/history.md` is not updated.

and i don't see bump in `src/CMakeLists.txt`:

```cmake
  set (LIBSAMPLERATE_ABI_VERSION_CURRENT 2)
  set (LIBSAMPLERATE_ABI_VERSION_REVISION 1)
  set (LIBSAMPLERATE_ABI_VERSION_AGE 2)
```

**Comment by SoapGentoo** [comment]
I actually looked at `docs/history.md` and wondered: what utility does that file provide? For the `github.io` pages?

**Comment by evpobr** [comment]
G

> I actually looked at `docs/history.md` and wondered: what utility does that file provide? For the `github.io` pages?

Yes, GitHub generates our site: http://libsndfile.github.io/libsamplerate/history.html.

**Comment by SoapGentoo** [comment]
suggestions? Like I'm not even sure what to condense the current changes down to. Also, please check #170 before I cut the release.

**Comment by evpobr** [comment]
Fix ABI version incompatibility between Autotools and CMake build on Apple platforms. Minor bug fixes and upates.

**Review by evpobr — APPROVED** [review]

**Comment by SoapGentoo** [comment]
I'll push the commit and tarballs tomorrow.

**Comment by evpobr** [comment]
Ok.

**Pull request closed without merging**
